# Generated by Django 4.2.3 on 2023-08-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_song_artist_delete_artist_delete_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='audio_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='add something', verbose_name='body'),
        ),
    ]
