# Generated by Django 4.2.3 on 2023-08-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_options_remove_post_body_post_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='post',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='post',
            name='song',
        ),
    ]
