# Generated by Django 4.2.3 on 2023-08-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_artist_remove_post_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='audio_link',
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default='https://www.vibstream.com'),
        ),
    ]
