# Generated by Django 4.2.3 on 2023-08-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_art',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='vibe',
            field=models.FileField(blank=True, null=True, upload_to='vibes/'),
        ),
    ]
