# Generated by Django 4.2.3 on 2023-08-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
