# Generated by Django 4.2.3 on 2023-08-07 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metaversemusic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(choices=[('Dancehall', 'Dancehall'), ('Hip Hop', 'Hip Hop'), ('Reggae', 'Reggae'), ('Trini Dancehall', 'Trini Dancehall'), ('Trap', 'Trap'), ('Soca', 'Soca'), ('Calypso', 'Calypso'), ('Samba', 'Samba'), ('Afro Beat', 'Afro Beat'), ('RnB', 'RnB'), ('House', 'House'), ('Electronic', 'Electronic'), ('Rock', 'Rock'), ('Country', 'Country')], default='Dancehall', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='song_ids',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='tags',
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('album', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.DateTimeField()),
                ('song_file', models.FileField(blank=True, null=True, upload_to='')),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('composer', models.CharField(blank=True, max_length=100, null=True)),
                ('artist', models.ManyToManyField(blank=True, related_name='songs', to='metaversemusic.artist')),
                ('genre', models.ManyToManyField(blank=True, related_name='songs', to='metaversemusic.genre')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='genres',
            field=models.ManyToManyField(related_name='playlists', to='metaversemusic.genre'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlists', to='metaversemusic.song'),
        ),
        migrations.AlterField(
            model_name='charts',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='metaversemusic.song'),
        ),
    ]
