# Generated by Django 4.2.3 on 2023-08-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaversemusic', '0002_artist_genre_remove_playlist_song_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
