# Generated by Django 4.2.3 on 2023-08-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaversemusic', '0004_remove_song_uploaded_by_remove_song_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_name',
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_name',
            field=models.ManyToManyField(related_name='artist', to='metaversemusic.genre'),
        ),
    ]
