# Generated by Django 4.2.3 on 2023-08-26 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metaversemusic', '0005_remove_artist_artist_name_artist_artist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='choices',
            new_name='genre_choice',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='saved_by',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_name',
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='nfts')),
                ('music', models.FileField(upload_to='nfts')),
                ('album', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.DateTimeField()),
                ('artist_name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('composer', models.CharField(blank=True, max_length=100, null=True)),
                ('token_id', models.BigIntegerField()),
                ('minting_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('royalty_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('genre', models.ManyToManyField(blank=True, related_name='genre', to='metaversemusic.genre')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='nfts',
            field=models.ManyToManyField(related_name='artists', to='metaversemusic.nft'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charts',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='metaversemusic.nft'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlists', to='metaversemusic.nft'),
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
